<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saikethan_R" failures="0" tests="10" name="com.parabank.tests.LoginTests" time="55.282" errors="1" timestamp="2025-09-08T10:48:46 IST" skipped="0">
  <testcase classname="com.parabank.tests.LoginTests" name="validLogin" time="12.339"/>
  <testcase classname="com.parabank.tests.LoginTests" name="multipleInvalidAttempts" time="12.606"/>
  <testcase classname="com.parabank.tests.LoginTests" name="invalidLoginWrongPassword" time="4.487"/>
  <testcase classname="com.parabank.tests.LoginTests" name="invalidLoginWrongUser" time="5.832"/>
  <testcase classname="com.parabank.tests.LoginTests" name="loginWithoutPassword" time="3.465">
    <error message="Unresolved compilation problems: 
	lp cannot be resolved
	lp cannot be resolved
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
lp cannot be resolved
lp cannot be resolved

at com.parabank.tests.LoginTests.loginWithoutPassword(LoginTests.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- loginWithoutPassword -->
  <testcase classname="com.parabank.tests.LoginTests" name="emptyCredentials" time="3.705"/>
  <testcase classname="com.parabank.tests.LoginTests" name="logoutAfterLogin" time="4.032"/>
  <testcase classname="com.parabank.tests.LoginTests" name="validLoginWithUppercasePassword" time="2.237"/>
  <testcase classname="com.parabank.tests.LoginTests" name="validLoginWithUppercaseUsername" time="2.830"/>
  <testcase classname="com.parabank.tests.LoginTests" name="loginWithoutUsername" time="3.749"/>
</testsuite> <!-- com.parabank.tests.LoginTests -->
